services:
  database:
    image: mysql:9
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-app}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-!ChangeMe!}
    restart: unless-stopped
    volumes:
      - database_data:/var/lib/mysql

  meilisearch:
    image: getmeili/meilisearch:${MEILISEARCH_VERSION:-v1.14}
    ports:
      - "7700:7700"
    environment:
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY:-!ChangeMe!}
    volumes:
      - meilisearch_data:/meili_data

volumes:
  database_data:
  meilisearch_data:
